// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxnMD4KkBB0KFUu79RZ6DNZ0ssvSYwzbU',
    appId: '1:510605352841:web:847578f2b17a409d5ccb58',
    messagingSenderId: '510605352841',
    projectId: 'musicplayer-c4935',
    authDomain: 'musicplayer-c4935.firebaseapp.com',
    storageBucket: 'musicplayer-c4935.appspot.com',
    measurementId: 'G-FT0GXZ4J1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQ822GqXOuSfNmFoF9nKlLUboinWgEYU',
    appId: '1:525561092310:web:74ee9c23314a9ad250d177',
    messagingSenderId: '525561092310',
    projectId: 'bedev-mp3',
    storageBucket: 'bedev-mp3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESQK9UL4jTODV-ya7vS73eT2ILmHTeSE',
    appId: '1:510605352841:ios:16fa2f8c4773a1535ccb58',
    messagingSenderId: '510605352841',
    projectId: 'musicplayer-c4935',
    storageBucket: 'musicplayer-c4935.appspot.com',
    androidClientId: '510605352841-ih7ft1rrjsolkboogs2gtla0s53pljfd.apps.googleusercontent.com',
    iosClientId: '510605352841-6ntd69i377jvcv2l19g35p9rtb6ffe0j.apps.googleusercontent.com',
    iosBundleId: 'com.aplikasii.mp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAESQK9UL4jTODV-ya7vS73eT2ILmHTeSE',
    appId: '1:510605352841:ios:16fa2f8c4773a1535ccb58',
    messagingSenderId: '510605352841',
    projectId: 'musicplayer-c4935',
    storageBucket: 'musicplayer-c4935.appspot.com',
    androidClientId: '510605352841-ih7ft1rrjsolkboogs2gtla0s53pljfd.apps.googleusercontent.com',
    iosClientId: '510605352841-6ntd69i377jvcv2l19g35p9rtb6ffe0j.apps.googleusercontent.com',
    iosBundleId: 'com.aplikasii.mp3',
  );
}
